### ISSUE TITLE
RMod.exe failed to inject rMod.dll

### ISSUE THREAD

**Issue by GemsKnight** [atom0s/rMod#1]
Windows Version: Windows 10 x64 - v1903 - OS version 18362.356
rMod Version: v1.0.0.1
Game Version: Origin
Game Version Number: the lastest (24.09.2019)

After setting the path to my Recknoning.exe and launch rMode.exe as admin, it says it failed to inject rMod.dll.

I didn't find any documentation about it
![rModerror]
(https://user-images.githubusercontent.com/22448962/65537892-73f8e500-df06-11e9-8b23-4d391b2f5abd.PNG)

**Comment by atom0s** [comment]
Few things to check:

  * Make sure you have the proper requirements to run rMod.
  * Make sure that you have proper permissions to the folder you are running from.
  * Make sure that you are running rMod as admin. (Right-click > Run as Administrator)
  * Make sure your anti-virus is not affecting the injection.

Lastly, if you have any modifications installed like ENB, dgVoodoo, ReShade, etc. try removing/disabling them.

**Comment by GemsKnight** [comment]
It was because of an ENB I used (SweetFX).
It also use an injector and I'm pretty sure it was because of this.

Thank you for your work !
